const constants = {
    TITLE_AUTHOR: "Tác giả:",
    TITLE_PUBLISHER: "Nhà xuất bản:",
    TITLE_YEAR_OF_PUBLISH: "Năm xuất bản:",
    TITLE_DESCRIPTION: "Giới thiệu sách",
    TITLE_RELATED_BOOK: "Các sách liên quan:",
    TITLE_LIST_RATING: "Đánh giá sản phẩm",
    TITLE_DONT_HAVE_RATING: "Không có đánh giá nào",
    TITLE_RATING: "Đánh giá của bạn",
    TITLE_FIRST_RATING: "1. Đánh giá của bạn về sản phẩm này:  ",
    TITLE_SECOND_RATING: "2. Viết nhận xét của bạn:  ",
    TEXT_RATING: "đánh giá",
    TEXT_BUTTON_RATING: "Gửi đánh giá",
    TEXT_BUTTON_UPDATE_RATING: "Chỉnh sửa đánh giá",
    TEXT_QUANTITY: "Số lượng: ",
    TEXT_ADD_TO_CART: "Thêm vào giỏ hàng",
    TEXT_ORDER: "Mua hàng",
    MAX_STAR: 5,
}
export default constants;