const testData = [
    {
        bookId: 1,
        bookName: "Bến Xe (Tái Bản 2020)",
        nxb: "NXB Văn học",
        auth: "Thương Thái Vy",
        year: 2020,
        price: 76000,
        quantity: 80,
        sale: 0.8,
        description: "Đây là quyển sạch tuyệt vời với những nội dung tuyệt vời",
        imageURL: "https://cdn0.fahasa.com/media/catalog/product/8/9/8935212349208.jpg",
        rate: 3.5,
    },
    {
        bookId: 2,
        bookName: "Bến Xe 2 (Tái Bản 2020)",
        nxb: "NXB Văn học",
        auth: "Thương Thái Vy",
        year: 2020,
        price: 76000,
        quantity: 80,
        sale: 0.8,
        description: "Đây là quyển sạch tuyệt vời với những nội dung tuyệt vời",
        imageURL: "https://cdn0.fahasa.com/media/catalog/product/8/9/8935212349208.jpg",
        rate: 3.5,
    },
    {
        bookId: 3,
        bookName: "Bến Xe 3 (Tái Bản 2020)",
        nxb: "NXB Văn học",
        auth: "Thương Thái Vy",
        year: 2020,
        price: 76000,
        quantity: 80,
        sale: 0.8,
        description: "Đây là quyển sạch tuyệt vời với những nội dung tuyệt vời",
        imageURL: "https://cdn0.fahasa.com/media/catalog/product/8/9/8935212349208.jpg",
        rate: 3.5,
    },
    {
        bookId: 4,
        bookName: "Bến Xe 4 (Tái Bản 2020)",
        nxb: "NXB Văn học",
        auth: "Thương Thái Vy",
        year: 2020,
        price: 76000,
        quantity: 80,
        sale: 0.8,
        description: "Đây là quyển sạch tuyệt vời với những nội dung tuyệt vời",
        imageURL: "https://cdn0.fahasa.com/media/catalog/product/8/9/8935212349208.jpg",
        rate: 3.5,
    },
    {
        bookId: 5,
        bookName: "Bến Xe 5 (Tái Bản 2020)",
        nxb: "NXB Văn học",
        auth: "Thương Thái Vy",
        year: 2020,
        price: 76000,
        quantity: 80,
        sale: 0.8,
        description: "Đây là quyển sạch tuyệt vời với những nội dung tuyệt vời",
        imageURL: "https://cdn0.fahasa.com/media/catalog/product/8/9/8935212349208.jpg",
        rate: 3.5,
    }
]
export default testData